version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - pip install toml
      - export MODEL_NAME=$(python -c "import toml; config = toml.load('pyproject.toml'); print(config['project']['name'])")
      - export PROJECT_VERSION=$(python -c "import toml; config = toml.load('pyproject.toml'); print(config['project']['version'])")
      - chmod +x ./bin/pre-build.sh
      - ./bin/pre-build.sh
  build:
    commands:
      - echo [hosta] Build started on `date`
      - echo [hosta] Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - DOCKER_CLIENT_TIMEOUT=60000 docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG